[package]
name = "reth-dns-discovery"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Support for EIP-1459 Node Discovery via DNS"

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-net-common = { path = "../common" }
reth-rlp = { path = "../../rlp" }

# ethereum
secp256k1 = { version = "0.26.0", features = [
    "global-context",
    "rand-std",
    "recovery",
    "serde"
] }
enr = { version = "0.8.0", default-features = false, features = ["rust-secp256k1"] }

# async/futures
tokio = { version = "1", features = ["io-util", "net", "time"] }
tokio-stream = "0.1"

# trust-dns
trust-dns-resolver = "0.22"

# misc
data-encoding = "2"
async-trait = "0.1"
linked_hash_set = "0.1"
schnellru = "0.2"
thiserror = "1.0"
tracing = "0.1"
parking_lot = "0.12"
serde = { version = "1.0", optional = true }
serde_with = { version = "2.1.0", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread"] }
reth-tracing = { path = "../../tracing" }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_with"]
